#### general settings
name: patches-vgg_loss_negative_sign
use_tb_logger: true
model: SRFL_Glow
distortion: sr
scale: 4
gpu_ids: [0,] # should be equal to $CUDA_VISIBLE_DEVICES


#### datasets
datasets:
  train:
    name: Iphone_DSLR_tr
    mode: LQGT_multiclass
    dataroot_GT: [../datasets/DPED patches/iphone/training_data/canon/1x/,
                  ../datasets/DPED patches/iphone/training_data/iphone/1x/]
    dataroot_LQ: [../datasets/DPED patches/iphone/training_data/canon/4x/,
                  ../datasets/DPED patches/iphone/training_data/iphone/4x/]

    n_workers: 4  # per GPU
    preload: False # set true to load images into ram for faster training
    batch_size: 16
    balanced: True
    use_shuffle: true
    use_flip: False
    use_crop: true
    color: RGB
    GT_size: 96
    quant: 32
    
  val:
    name: Iphone_DSLR_va
    mode: LQGT_multiclass
    dataroot_GT: [ ../datasets/DPED patches/iphone/test_data/patches/canon/1x/,
                   ../datasets/DPED patches/iphone/test_data/patches/iphone/1x/ ]
    dataroot_LQ: [ ../datasets/DPED patches/iphone/test_data/patches/canon/4x/,
                   ../datasets/DPED patches/iphone/test_data/patches/iphone/4x/ ]

    preload: False # set true to load images into ram for faster training
    center_crop_hr_size: 96
    quant: 32
    n_max: 10
 
  patches:
    name: Patches_Iphone_DSLR_tr
    mode: LQGT_multiclass
    dataroot_GT: [../datasets/DPED patches/iphone/training_data/canon/1x/,
                  ../datasets/DPED patches/iphone/training_data/iphone/1x/]
    dataroot_LQ: [../datasets/DPED patches/iphone/training_data/canon/4x/,
                  ../datasets/DPED patches/iphone/training_data/iphone/4x/]

    n_workers: 4  # per GPU
    preload: False # set true to load images into ram for faster training
    batch_size: 16
    balanced: True
    use_shuffle: true
    use_flip: False
    use_crop: true
    color: RGB
    GT_size: 96
    quant: 32

#### network structures
network_G:
  which_model_G: RRDBGlowNet
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 23
  upscale: 4
  train_RRDB: true

  flow:
    K: 16
    L: 3
    noInitialInj: true
    LU_decomposed: true
    coupling: CondAffineSeparatedAndCond
    additionalFlowNoAffine: 2
    split:
      enable: true
    fea_up0: true
    stackRRDB:
      blocks: [1, 8, 15, 22]
      concat: true
    shift:
      constant: correlated
      classes: [[0,1], ]
      std_init_shift: 0.0
    LR_noise_std: 0.03
    CondAffineSeparatedAndCond:
      eps: 0.001
      multReverse: True

#### path
path:
  root: D:/DeFlow/DeFlow/codes
  pretrain_model_G: ../trained_models/RRDB_models/RRDB_PSNR_x4.pth
  strict_load: true
  resume_state: auto

#### training settings: learning rate scheme, loss
train:
  manual_seed: 10
  lr_G: !!float 0.5e-5
  weight_decay_G: 0
  beta1: 0.9
  beta2: 0.99
  lr_scheme: MultiStepLR
  warmup_iter: -1  # no warm up
  lr_steps_rel: [0.5, 0.75, 0.9, 0.95]
  lr_gamma: 0.5
  dslr_forH: False
  niter: 20000
  val_freq: 2000
  weight_fl: 0.5
  vgg_loss:
    patches_vgg_exclusive: False
    is_vgg_loss: True
    type: none
    feature_layers: [ 3 ]
    print_vgg_loss: True
    weight_vgg_loss : 5

#### validation settings
val:
  heats: [1.0]
  n_sample: 1

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3