#### general settings
name: vgg_loss_block3
use_tb_logger: true
model: SRFL_Glow
distortion: sr
scale: 4
gpu_ids: [0,] # should be equal to $CUDA_VISIBLE_DEVICES


#### datasets
datasets:
  train:
    name: Iphone_DSLR_tr
    mode: LQGT_multiclass
    dataroot_GT: [ ../datasets/DPED-RO-SORTED/DPEDiphone-tr-x/4x/,           # DSLR clean 4x
                   ../datasets/DPED-RO-SORTED/DPEDiphone-tr-y/1x/ ]          # iphone clean 1x
    dataroot_LQ: [ ../datasets/DPED-RO-SORTED/DPEDiphone-tr-x/16x/,          # DSLR clean 16x
                   ../datasets/DPED-RO-SORTED/DPEDiphone-tr-y/4x/ ]          # iphone clean 4x

    # setup that didn't work well for DPED-RO:
#    dataroot_GT: [ ../datasets/DPED-RO/DPEDiphone-tr-y/4x/,
#                   ../datasets/DPED-RO/DPEDiphone-tr-x/1x/ ]
#    dataroot_LQ: [ ../datasets/DPED-RO/DPEDiphone-tr-y/16x/,
#                   ../datasets/DPED-RO/DPEDiphone-tr-x/4x_reshaped/ ]

    n_workers: 3  # per GPU

    preload: False # set true to load images into ram for faster training
    batch_size: 8
    balanced: True
    use_shuffle: true
    use_flip: true
    use_crop: true
    color: RGB
    GT_size: 160
    quant: 32
    
  val:
    name: Iphone_DSLR_va

    mode: LQGT_multiclass

    dataroot_GT: [ ../datasets/DPED-RO-SORTED/DPEDiphone-val-x/4x/,            # DSLR clean 4x
                   ../datasets/DPED-RO-SORTED/DPEDiphone-val-y/1x/ ]           # iphone clean 1x
    dataroot_LQ: [ ../datasets/DPED-RO-SORTED/DPEDiphone-val-x/16x/,           # DSLR clean 16x
                   ../datasets/DPED-RO-SORTED/DPEDiphone-val-y/4x/ ]           # iphone clean 4x

    # setup that didn't work well for DPED-RO:
#    dataroot_GT: [../datasets/DPED-RO/DPEDiphone-val-y/4x/,
#                  ../datasets/DPED-RO/DPEDiphone-val-x/1x]
#    dataroot_LQ: [../datasets/DPED-RO/DPEDiphone-val-y/16x/,
#                  ../datasets/DPED-RO/DPEDiphone-val-x/4x_reshaped/]

    preload: False # set true to load images into ram for faster training
    center_crop_hr_size: 160
    quant: 32
    n_max: 10
 
  patches:
    name: Patches_Iphone_DSLR_tr
    mode: LQGT_multiclass
    dataroot_GT: [ D:/Deep_Project/DeFlow/datasets/DPED patches/train/canon/1x/,
                   D:/Deep_Project/DeFlow/datasets/DPED patches/train/iphone/1x/ ]
    dataroot_LQ: [ D:/Deep_Project/DeFlow/datasets/DPED patches/train/canon/4x/,
                   D:/Deep_Project/DeFlow/datasets/DPED patches/train/iphone/4x/ ]

    n_workers: 0  # per GPU
    preload: False # set true to load images into ram for faster training
    batch_size: 1
    balanced: True
    use_shuffle: true
    use_flip: False
    use_crop: true
    color: RGB
    GT_size: 96
    quant: 32

#### network structures
network_G:
  which_model_G: RRDBGlowNet
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 23
  upscale: 4
  train_RRDB: true

  flow:
    K: 16
    L: 3
    noInitialInj: true
    LU_decomposed: true
    coupling: CondAffineSeparatedAndCond
    additionalFlowNoAffine: 2
    split:
      enable: true
    fea_up0: true
    stackRRDB:
      blocks: [1, 8, 15, 22]
      concat: true
    shift:
      constant: correlated
      classes: [[0,1], ]
      std_init_shift: 0.0
    LR_noise_std: 0.03
    CondAffineSeparatedAndCond:
      eps: 0.001
      multReverse: True

#### path
path:
  root: D:/DeFlow/DeFlow/codes
  pretrain_model_G: D:/Deep_Project/DeFlow/trained_models/RRDB_models/RRDB_PSNR_x4.pth
  strict_load: true
  resume_state: auto

#### training settings: learning rate scheme, loss
train:
  manual_seed: 10
  lr_G: !!float 0.5e-5
  weight_decay_G: 0
  beta1: 0.9
  beta2: 0.99
  lr_scheme: MultiStepLR
  warmup_iter: -1  # no warm up
  lr_steps_rel: [0.5, 0.75, 0.9, 0.95]
  lr_gamma: 0.5

  niter: 10000
  val_freq: 1000

  dslr_forH: False

  vgg_loss:
    patches_vgg_exclusive: False
    is_vgg_loss: True
    feature_layers: [ 3 ]
    print_vgg_loss: True


#### validation settings
val:
  heats: [1.0]
  n_sample: 1

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3

#### perceptual loss during train/val


